apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rust 
  janus-idp.io/tekton: rust
  backstage.io/kubernetes-id: rust
  backstage.io/kubernetes-namespace: rust-app 
  app.kubernetes.io/part-of: rust
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  