apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rust
  janus-idp.io/tekton: rust
  backstage.io/kubernetes-id: rust
  backstage.io/kubernetes-namespace: rust-app 
  app.kubernetes.io/part-of: rust
resources:
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
